### ISSUE TITLE
screenshot(s) please!

### ISSUE THREAD

**Issue by linuxcaffe** [vrutkovs/telch#38]
* Telch version: current
* Operating System: any, but in a browser

### Description
I think there's a demand for a nice web interface for taskwarrior, and screenshot says a lot, thanks!

**Comment by vrutkovs** [comment]
This is a great idea! Unfortunately my task DB fails to sync and seems to be corrupted - and Telch requires a sync. I'll try to fix it soon and add screenshots to README

**Comment by linuxcaffe** [comment]
oh THAT's annoying!  ;)  maybe visit irc.freenode.net #taskwarrior and maybe we can sort that out!

**Comment by vrutkovs** [comment]
Do these look good?

![image](https://user-images.githubusercontent.com/114501/29717895-33bb0bb4-89b1-11e7-9168-6536bf01f660.png)
![image](https://user-images.githubusercontent.com/114501/29717902-39a61546-89b1-11e7-89a5-892cb3a4e81b.png)

**Comment by ssbarnea** [comment]
Can you please put these on the homepage? A demo site would be very useful too.

**Comment by vrutkovs** [comment]
Fixed in 07fb79a810207d064e8c68a07ab9246bd7f04080
