### ISSUE TITLE
Link to the documentation in the README.md seems dead.

### ISSUE THREAD

**Issue by dannycolin** [vrutkovs/telch#66]
### Description

Link to the documentation in the README.md seems dead. (https://telch.readthedocs.io)

**Comment by vrutkovs** [comment]
Oh, right, there is 0 documentation now - and Read The Docs entry was not created at all

**Comment by dannycolin** [comment]
Oh I see. Maybe you should add a "coming soon" or something like that in the README.md ;)

**Comment by ssbarnea** [comment]
True and sad. Can we have this fixed? I hate when I have to drop evaluating a project due to issues like this.
